---
abstract: 'Perl extension for CSS minification'
author:
  - 'Simon Bertrang <janus@cpan.org>'
build_requires:
  Test::Differences: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Compressor
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.02
